name: Lint Project

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        container:
            image: node:22
        steps:
            - uses: actions/checkout@v4
              with:
                  node-version: 22
            - run: npm install -g pnpm
            - run: pnpm install
            - run: pnpm run lint
